# Generated by Django 3.2.9 on 2021-11-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_movie', models.CharField(max_length=200)),
                ('suggested_song', models.CharField(max_length=200)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getbetter.feeling')),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000000)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getbetter.solution')),
            ],
        ),
    ]
