# Generated by Django 3.2.9 on 2021-11-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getbetter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='suggested_song',
        ),
        migrations.CreateModel(
            name='solution2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_song', models.CharField(max_length=200)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getbetter.feeling')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='solution2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='getbetter.solution2'),
            preserve_default=False,
        ),
    ]
