# Generated by Django 3.2.9 on 2021-11-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getbetter', '0002_auto_20211110_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='solution2',
        ),
        migrations.RenameModel(
            old_name='solution2',
            new_name='solutionsong',
        ),
        migrations.CreateModel(
            name='linksong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000000)),
                ('solutionsong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getbetter.solutionsong')),
            ],
        ),
    ]
