# Generated by Django 3.2.9 on 2021-11-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getbetter', '0003_auto_20211110_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linksong',
            name='solutionsong',
        ),
        migrations.AddField(
            model_name='solution',
            name='link',
            field=models.CharField(default=1, max_length=2000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutionsong',
            name='link',
            field=models.CharField(default=1, max_length=2000000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='link',
        ),
        migrations.DeleteModel(
            name='linksong',
        ),
    ]
