# Generated by Django 3.2.8 on 2021-11-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getbetter', '0007_auto_20211112_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='feeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='getbetter.feeling'),
        ),
    ]
