# Generated by Django 3.2.8 on 2021-11-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getbetter', '0008_alter_solution_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionsong',
            name='feeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutionsongs', to='getbetter.feeling'),
        ),
    ]
