# Generated by Django 3.2.8 on 2021-11-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getbetter', '0009_alter_solutionsong_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='feeling_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='feeling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='getbetter.feeling'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='suggested_movie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solutionsong',
            name='feeling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutionsongs', to='getbetter.feeling'),
        ),
        migrations.AlterField(
            model_name='solutionsong',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutionsong',
            name='suggested_song',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
